export const dummyData = [
  {
    zipcode: "12345",
    typeOfShipping: "Standard",
    shippingCost: 5.99,
    deliveryDuration: 3,
    key: 830,
  },
  {
    zipcode: "54321",
    typeOfShipping: "Express",
    shippingCost: 12.99,
    deliveryDuration: 1,
    key: 436,
  },
  {
    zipcode: "98765",
    typeOfShipping: "Priority",
    shippingCost: 8.49,
    deliveryDuration: 2,
    key: 794,
  },
  {
    zipcode: "67890",
    typeOfShipping: "Standard",
    shippingCost: 6.99,
    deliveryDuration: 4,
    key: 646,
  },
  {
    zipcode: "23456",
    typeOfShipping: "Express",
    shippingCost: 15.99,
    deliveryDuration: 1,
    key: 783,
  },
  {
    zipcode: "87654",
    typeOfShipping: "Priority",
    shippingCost: 9.99,
    deliveryDuration: 2,
    key: 735,
  },
  {
    zipcode: "56789",
    typeOfShipping: "Standard",
    shippingCost: 7.99,
    deliveryDuration: 3,
    key: 330,
  },
  {
    zipcode: "32109",
    typeOfShipping: "Express",
    shippingCost: 14.49,
    deliveryDuration: 1,
    key: 107,
  },
  {
    zipcode: "90876",
    typeOfShipping: "Priority",
    shippingCost: 11.99,
    deliveryDuration: 2,
    key: 888,
  },
  {
    zipcode: "45678",
    typeOfShipping: "Standard",
    shippingCost: 6.49,
    deliveryDuration: 4,
    key: 977,
  },
];
